import * as github from '@actions/github';
import { exec, getExecOutput } from '@actions/exec';
import type { Logger } from '../util/logger.js';
import type { PrunerReport, PrunedEntry } from '../types.js';

export interface PullRequestOptions {
  cwd: string;
  token: string;
  branch: string;
  base: string;
  title: string;
  bodyHeader?: string;
  commitMessage: string;
  labels: string[];
  changedFiles: string[];
  reports: PrunerReport[];
  logger: Logger;
}

export interface PullRequestResult {
  number: number;
  url: string;
}

export async function ensureGitIdentity(cwd: string): Promise<void> {
  const name = process.env.GIT_AUTHOR_NAME ?? 'github-actions[bot]';
  const email = process.env.GIT_AUTHOR_EMAIL ?? '41898282+github-actions[bot]@users.noreply.github.com';
  await exec('git', ['config', 'user.name', name], { cwd });
  await exec('git', ['config', 'user.email', email], { cwd });
}

export async function hasChanges(cwd: string): Promise<boolean> {
  const out = await getExecOutput('git', ['status', '--porcelain'], { cwd, silent: true });
  return out.stdout.trim().length > 0;
}

export async function createPullRequest(opts: PullRequestOptions): Promise<PullRequestResult> {
  const { cwd, branch, base, title, commitMessage, changedFiles, reports, logger } = opts;
  const octokit = github.getOctokit(opts.token);
  const { owner, repo } = github.context.repo;

  await ensureGitIdentity(cwd);
  await exec('git', ['checkout', '-B', branch], { cwd });
  for (const file of changedFiles) {
    await exec('git', ['add', '--', file], { cwd });
  }
  await exec('git', ['commit', '-m', commitMessage], { cwd });
  await exec(
    'git',
    [
      'push',
      '--force-with-lease',
      `https://x-access-token:${opts.token}@github.com/${owner}/${repo}.git`,
      `${branch}:${branch}`,
    ],
    { cwd, silent: true },
  );

  const existing = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: 'open',
  });

  let pr: { number: number; html_url: string };
  if (existing.data.length > 0) {
    pr = existing.data[0]!;
    logger.info(`Updated existing PR #${pr.number} (${pr.html_url})`);
  } else {
    const created = await octokit.rest.pulls.create({
      owner,
      repo,
      head: branch,
      base,
      title,
      body: renderBody(reports, opts.bodyHeader),
    });
    pr = created.data;
    logger.info(`Opened PR #${pr.number} (${pr.html_url})`);
  }

  if (opts.labels.length > 0) {
    await octokit.rest.issues.addLabels({
      owner,
      repo,
      issue_number: pr.number,
      labels: opts.labels,
    });
  }

  return { number: pr.number, url: pr.html_url };
}

export function renderBody(reports: PrunerReport[], header?: string): string {
  const lines: string[] = [];
  if (header) {
    lines.push(header.trim());
    lines.push('');
  }
  lines.push(
    'This pull request is generated by [`prune-supply-chain-overrides-action`](https://github.com/marketplace/actions/prune-supply-chain-overrides).',
  );
  lines.push('');
  lines.push(
    'Entries below were originally added as supply-chain mitigations and have since become unnecessary, so the action removed them.',
  );
  lines.push('');

  for (const report of reports) {
    if (report.removed.length === 0 && report.skipped.length === 0) continue;
    lines.push(`### ${report.pruner}`);
    lines.push('');
    if (report.removed.length > 0) {
      lines.push('**Removed**');
      lines.push('');
      for (const entry of report.removed) {
        lines.push(`- \`${entry.key}\`${entry.value ? ` (\`${entry.value}\`)` : ''} — ${entry.reason}`);
      }
      lines.push('');
    }
    if (report.skipped.length > 0) {
      lines.push('<details><summary>Skipped (kept)</summary>');
      lines.push('');
      for (const entry of report.skipped) {
        lines.push(`- \`${entry.key}\` — ${entry.reason}`);
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }
  return lines.join('\n');
}

export function summarizeRemovals(reports: PrunerReport[]): PrunedEntry[] {
  return reports.flatMap((r) => r.removed);
}
